name: Futurerestore

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
      - shell: msys2 {0}
        run: |
          sh $(GITHUB_WORKSPACE)/futurerestore/futurerestore/.github/workflows/win-build.sh
