name: Futurerestore

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          fetch-depth: 0
      - uses: msys2/setup-msys2@v2
      - shell: msys2 {0}
        run: |
          sh D:/a/futurerestore/futurerestore/.github/workflows/win-build.sh
