name: Futurerestore

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          fetch-depth: 0
      - name: Windows Build
        id: Windows
        uses: msys2/setup-msys2@v2
        shell: msys2 {0}
        run: |
          sh $(GITHUB_WORKSPACE)/futurerestore/futurerestore/.github/workflows/win-build.sh
      - name: futurerestore Linux x86_64 RELEASE Archive
        id: futurerestore-Linux-x86_64-RELEASE-Archive
        uses: actions/upload-artifact@v2
        with:
          name: futurerestore-Linux-x86_64-RELEASE
          path: |
            $(GITHUB_WORKSPACE)/futurerestore/futurerestore/.github/workflows/futurerestore-Linux-x86_64*-RELEASE.tar.xz
      - name: futurerestore Linux x86_64 DEBUG Archive
        id: futurerestore-Linux-x86_64-DEBUG-Archive
        uses: actions/upload-artifact@v2
        with:
          name: futurerestore-Linux-x86_64-DEBUG
          path: |
            /home/runner/work/futurerestore/futurerestore/.github/workflows/futurerestore-Linux-x86_64*-DEBUG.tar.xz
      - name: futurerestore Linux x86_64 ASAN Archive
        id: futurerestore-Linux-x86_64-ASAN-Archive
        uses: actions/upload-artifact@v2
        with:
          name: futurerestore-Linux-x86_64-ASAN
          path: |
            /home/runner/work/futurerestore/futurerestore/.github/workflows/futurerestore-Linux-x86_64*-ASAN.tar.xz
